export interface Event {
  id: string;
  title: string;
  description: string;
  date: string;
  time: string;
  location: string;
  city: string;
  type: 'webinar' | 'workshop' | 'conference' | 'networking';
  imageUrl: string;
  ticketUrl: string;
  price: string;
  organizer: string;
}

// Mock event list (20 events with correct types and images)
const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Women in Tech Conference',
    description: 'A conference for women in technology to network and learn.',
    date: '2024-06-10',
    time: '10:00 AM',
    location: 'Taj Palace',
    city: 'Delhi',
    type: 'conference',
    imageUrl: '/1.png',
    ticketUrl: 'https://example.com/event/1',
    price: '₹1,000',
    organizer: 'Women Who Code',
  },
  {
    id: '2',
    title: 'SheLeads Workshop',
    description: 'Leadership workshop for aspiring women leaders.',
    date: '2024-06-12',
    time: '2:00 PM',
    location: 'The Oberoi',
    city: 'Mumbai',
    type: 'workshop',
    imageUrl: '/2.png',
    ticketUrl: 'https://example.com/event/2',
    price: '₹800',
    organizer: 'SheLeads India',
  },
  {
    id: '3',
    title: 'Digital Marketing Webinar',
    description: 'Learn digital marketing skills from industry experts.',
    date: '2024-06-15',
    time: '5:00 PM',
    location: 'Online',
    city: 'All Cities',
    type: 'webinar',
    imageUrl: '/3.png',
    ticketUrl: 'https://example.com/event/3',
    price: 'Free',
    organizer: 'Women Marketers',
  },
  {
    id: '4',
    title: 'Women Entrepreneurs Networking',
    description: 'Networking event for women entrepreneurs.',
    date: '2024-06-18',
    time: '6:00 PM',
    location: 'Hyatt Regency',
    city: 'Bangalore',
    type: 'networking',
    imageUrl: '/4.png',
    ticketUrl: 'https://example.com/event/4',
    price: '₹500',
    organizer: 'Startup Women',
  },
  {
    id: '5',
    title: 'Women in STEM Conference',
    description: 'Panel discussion with women leaders in STEM.',
    date: '2024-06-20',
    time: '11:00 AM',
    location: 'IIT Madras',
    city: 'Chennai',
    type: 'conference',
    imageUrl: '/5.png',
    ticketUrl: 'https://example.com/event/5',
    price: '₹1,200',
    organizer: 'STEM India',
  },
  {
    id: '6',
    title: 'Women in Finance Workshop',
    description: 'Workshop on financial literacy for women.',
    date: '2024-06-22',
    time: '3:00 PM',
    location: 'JW Marriott',
    city: 'Pune',
    type: 'workshop',
    imageUrl: '/6.png',
    ticketUrl: 'https://example.com/event/6',
    price: '₹700',
    organizer: 'Finance for Her',
  },
  {
    id: '7',
    title: 'Women in Art Conference',
    description: 'Showcasing art by women artists.',
    date: '2024-06-25',
    time: '4:00 PM',
    location: 'Art Gallery',
    city: 'Kolkata',
    type: 'conference',
    imageUrl: '/7.png',
    ticketUrl: 'https://example.com/event/7',
    price: '₹300',
    organizer: 'Art Women',
  },
  {
    id: '8',
    title: 'Women in Sports Networking',
    description: 'Meetup for women athletes and sports enthusiasts.',
    date: '2024-06-28',
    time: '7:00 PM',
    location: 'Sports Complex',
    city: 'Hyderabad',
    type: 'networking',
    imageUrl: '/8.png',
    ticketUrl: 'https://example.com/event/8',
    price: '₹400',
    organizer: 'Sports Women',
  },
  {
    id: '9',
    title: 'Women in Business Conference',
    description: 'Conference for women in business and management.',
    date: '2024-07-01',
    time: '9:00 AM',
    location: 'Taj Bengal',
    city: 'Kolkata',
    type: 'conference',
    imageUrl: '/9.png',
    ticketUrl: 'https://example.com/event/9',
    price: '₹1,500',
    organizer: 'Business Women India',
  },
  {
    id: '10',
    title: 'Women in Education Webinar',
    description: 'Webinar on women in education sector.',
    date: '2024-07-03',
    time: '8:00 PM',
    location: 'Online',
    city: 'All Cities',
    type: 'webinar',
    imageUrl: '/10.png',
    ticketUrl: 'https://example.com/event/10',
    price: 'Free',
    organizer: 'EduWomen',
  },
  {
    id: '11',
    title: 'Women in Law Workshop',
    description: 'Workshop for women in the legal profession.',
    date: '2024-07-05',
    time: '1:00 PM',
    location: 'High Court',
    city: 'Delhi',
    type: 'workshop',
    imageUrl: '/11.png',
    ticketUrl: 'https://example.com/event/11',
    price: '₹900',
    organizer: 'Law Women',
  },
  {
    id: '12',
    title: 'Women in Healthcare Conference',
    description: 'Conference for women in healthcare.',
    date: '2024-07-08',
    time: '10:00 AM',
    location: 'Apollo Hospital',
    city: 'Chennai',
    type: 'conference',
    imageUrl: '/12.png',
    ticketUrl: 'https://example.com/event/12',
    price: '₹1,100',
    organizer: 'Health Women',
  },
  {
    id: '13',
    title: 'Women in Media Networking',
    description: 'Networking event for women in media.',
    date: '2024-07-10',
    time: '6:00 PM',
    location: 'Media House',
    city: 'Mumbai',
    type: 'networking',
    imageUrl: '/13.png',
    ticketUrl: 'https://example.com/event/13',
    price: '₹600',
    organizer: 'Media Women',
  },
  {
    id: '14',
    title: 'Women in Science Webinar',
    description: 'Webinar for women in science.',
    date: '2024-07-12',
    time: '7:00 PM',
    location: 'Online',
    city: 'All Cities',
    type: 'webinar',
    imageUrl: '/14.png',
    ticketUrl: 'https://example.com/event/14',
    price: 'Free',
    organizer: 'Science Women',
  },
  {
    id: '15',
    title: 'Women in Social Work Workshop',
    description: 'Workshop for women in social work.',
    date: '2024-07-15',
    time: '2:00 PM',
    location: 'NGO Center',
    city: 'Delhi',
    type: 'workshop',
    imageUrl: '/15.png',
    ticketUrl: 'https://example.com/event/15',
    price: '₹500',
    organizer: 'Social Women',
  },
  {
    id: '16',
    title: 'Women in Environment Conference',
    description: 'Conference on women and environment.',
    date: '2024-07-18',
    time: '11:00 AM',
    location: 'Eco Park',
    city: 'Hyderabad',
    type: 'conference',
    imageUrl: '/16.png',
    ticketUrl: 'https://example.com/event/16',
    price: '₹1,300',
    organizer: 'Eco Women',
  },
  {
    id: '17',
    title: 'Women in Politics Networking',
    description: 'Meetup for women in politics.',
    date: '2024-07-20',
    time: '5:00 PM',
    location: 'Assembly Hall',
    city: 'Bangalore',
    type: 'networking',
    imageUrl: '/17.png',
    ticketUrl: 'https://example.com/event/17',
    price: '₹700',
    organizer: 'Politics Women',
  },
  {
    id: '18',
    title: 'Women in Literature Workshop',
    description: 'Workshop for women writers.',
    date: '2024-07-22',
    time: '3:00 PM',
    location: 'Library',
    city: 'Pune',
    type: 'workshop',
    imageUrl: '/18.png',
    ticketUrl: 'https://example.com/event/18',
    price: '₹400',
    organizer: 'Literature Women',
  },
  {
    id: '19',
    title: 'Women in Design Conference',
    description: 'Conference for women in design.',
    date: '2024-07-25',
    time: '10:00 AM',
    location: 'Design Hub',
    city: 'Ahmedabad',
    type: 'conference',
    imageUrl: '/19.png',
    ticketUrl: 'https://example.com/event/19',
    price: '₹1,000',
    organizer: 'Design Women',
  },
  {
    id: '20',
    title: 'Women in Tech Networking',
    description: 'Networking event for women in tech.',
    date: '2024-07-28',
    time: '6:00 PM',
    location: 'Tech Park',
    city: 'Bangalore',
    type: 'networking',
    imageUrl: '/20.png',
    ticketUrl: 'https://example.com/event/20',
    price: '₹600',
    organizer: 'Tech Women',
  },
];

export async function fetchAllEvents(city?: string, type?: string): Promise<Event[]> {
  let events = mockEvents;
  if (city && city !== 'All Cities') {
    events = events.filter(event => event.city === city);
  }
  if (type && type !== 'All Types') {
    events = events.filter(event => event.type === type.toLowerCase());
  }
  return events.sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());
} 